// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

public partial class FileCsvContext : DbContext
{
    public FileCsvContext()
    {
    }

    public FileCsvContext(DbContextOptions<FileCsvContext> options)
        : base(options)
    {
    }

    public virtual DbSet<score> scores { get; set; }

    public virtual DbSet<student> students { get; set; }

    public virtual DbSet<subject> subjects { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=MINHNGUYEN\\MINHNGUYEN;Initial Catalog=FileCsv;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<score>(entity =>
        {
            entity.HasKey(e => e.score_id).HasName("PK__score__8CA19050BCE22F13");

            entity.HasOne(d => d.student).WithMany(p => p.scores).HasConstraintName("FK_score_student");

            entity.HasOne(d => d.subject).WithMany(p => p.scores).HasConstraintName("FK_score_subject");
        });

        modelBuilder.Entity<student>(entity =>
        {
            entity.HasKey(e => e.student_id).HasName("PK__student__2A33069A0A83FADF");
        });

        modelBuilder.Entity<subject>(entity =>
        {
            entity.HasKey(e => e.subject_id).HasName("PK__subject__5004F660C416D074");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}