// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("score")]
public partial class score
{
    [Key]
    public int score_id { get; set; }

    public int? subject_id { get; set; }

    public int? student_id { get; set; }

    public int? year { get; set; }

    [Column("score")]
    public double? score1 { get; set; }

    [ForeignKey("student_id")]
    [InverseProperty("scores")]
    public virtual student student { get; set; }

    [ForeignKey("subject_id")]
    [InverseProperty("scores")]
    public virtual subject subject { get; set; }
}