// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("student")]
public partial class student
{
    [Key]
    public int student_id { get; set; }

    [StringLength(50)]
    public string province_name { get; set; }

    public int? student_code { get; set; }

    [InverseProperty("student")]
    public virtual ICollection<score> scores { get; set; } = new List<score>();
}