// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("subject")]
public partial class subject
{
    [Key]
    public int subject_id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string subject_name { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string subject_code { get; set; }

    [InverseProperty("subject")]
    public virtual ICollection<score> scores { get; set; } = new List<score>();
}